[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$ProjectPath,

  [ValidateSet("Report", "Apply")]
  [string]$Mode = "Report",

  [ValidateRange(1, 100)]
  [int]$KeepRecent = 10
)

$ErrorActionPreference = "Stop"

$ResolvedProject = (Resolve-Path -LiteralPath $ProjectPath).Path
$ProjectRoot = [IO.Path]::GetFullPath($ResolvedProject)
$ChangesRoot = Join-Path $ProjectRoot "docs\changes"
$ArchiveRoot = Join-Path $ChangesRoot "archive"
$IndexPath = Join-Path $ChangesRoot "INDEX.md"
$NotePattern = '^\d{4}-\d{2}-\d{2}T\d{6}Z-[a-z0-9][a-z0-9-]*\.md$'

if (-not (Test-Path -LiteralPath (Join-Path $ProjectRoot "README.md") -PathType Leaf)) {
  throw "ProjectPath does not contain README.md: $ProjectRoot"
}
if (-not (Test-Path -LiteralPath $ChangesRoot -PathType Container)) {
  throw "Missing continuity directory: $ChangesRoot"
}

function Get-HotNotes {
  return @(
    Get-ChildItem -LiteralPath $ChangesRoot -File |
      Where-Object { $_.Name -match $NotePattern } |
      Sort-Object Name -Descending
  )
}

function Get-RelativeMarkdownPath {
  param([string]$BasePath, [string]$TargetPath)
  $BaseUri = [Uri](([IO.Path]::GetFullPath($BasePath).TrimEnd('\') + '\'))
  $TargetUri = [Uri][IO.Path]::GetFullPath($TargetPath)
  return [Uri]::UnescapeDataString($BaseUri.MakeRelativeUri($TargetUri).ToString())
}

$Notes = Get-HotNotes
$ToArchive = @($Notes | Select-Object -Skip $KeepRecent)

Write-Host "Project: $ProjectRoot"
Write-Host "Hot notes: $($Notes.Count); keep: $KeepRecent; archive candidates: $($ToArchive.Count)"

foreach ($Note in $ToArchive) {
  $Year = $Note.Name.Substring(0, 4)
  $Month = $Note.Name.Substring(5, 2)
  $TargetDirectory = Join-Path (Join-Path $ArchiveRoot $Year) $Month
  $TargetPath = Join-Path $TargetDirectory $Note.Name

  if ($Mode -eq "Report") {
    Write-Host "Would archive: $($Note.Name) -> archive/$Year/$Month/"
    continue
  }

  if (Test-Path -LiteralPath $TargetPath) {
    throw "Archive target already exists; refusing overwrite: $TargetPath"
  }
  New-Item -ItemType Directory -Path $TargetDirectory -Force | Out-Null
  Move-Item -LiteralPath $Note.FullName -Destination $TargetPath
  Write-Host "Archived: $($Note.Name) -> archive/$Year/$Month/"
}

if ($Mode -eq "Report") {
  Write-Host "Report only; no files changed."
  exit 0
}

$HotNotes = Get-HotNotes
$ArchivedNotes = if (Test-Path -LiteralPath $ArchiveRoot -PathType Container) {
  @(Get-ChildItem -LiteralPath $ArchiveRoot -File -Recurse | Where-Object { $_.Name -match $NotePattern })
} else {
  @()
}

$Lines = New-Object System.Collections.Generic.List[string]
$Lines.Add("# Change history index")
$Lines.Add("")
$Lines.Add("> Generated by `scripts/manage-project-history.ps1`; do not edit by hand.")
$Lines.Add("")
$Lines.Add("## Recent notes")
$Lines.Add("")
if ($HotNotes.Count -eq 0) {
  $Lines.Add("- No change notes yet.")
} else {
  foreach ($Note in $HotNotes) {
    $Lines.Add("- [$($Note.BaseName)](./$($Note.Name))")
  }
}
$Lines.Add("")
$Lines.Add("## Archive")
$Lines.Add("")
if ($ArchivedNotes.Count -eq 0) {
  $Lines.Add("- No archived notes yet.")
} else {
  $Groups = $ArchivedNotes | Group-Object {
    Split-Path -Parent (Get-RelativeMarkdownPath -BasePath $ArchiveRoot -TargetPath $_.FullName)
  } | Sort-Object Name -Descending
  foreach ($Group in $Groups) {
    $ArchiveLink = "./archive/$($Group.Name.Replace('\', '/'))/"
    $Lines.Add("- [$($Group.Name.Replace('\', '/'))]($ArchiveLink) - $($Group.Count) notes")
  }
}
$Lines.Add("")
$Lines.Add("Hot set: $($HotNotes.Count). Archived: $($ArchivedNotes.Count).")

$Encoding = New-Object Text.UTF8Encoding($false)
$TemporaryIndex = Join-Path $ChangesRoot (".INDEX.{0}.tmp" -f [Guid]::NewGuid().ToString("N"))
try {
  [IO.File]::WriteAllLines($TemporaryIndex, $Lines, $Encoding)
  Move-Item -LiteralPath $TemporaryIndex -Destination $IndexPath -Force
} finally {
  if (Test-Path -LiteralPath $TemporaryIndex) {
    Remove-Item -LiteralPath $TemporaryIndex -Force
  }
}

Write-Host "Updated index: $IndexPath"
